<?php

namespace ContainerFLTWfKP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateNewsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Infrastructure\Http\News\Controller\GenerateNewsController' shared autowired service.
     *
     * @return \App\Infrastructure\Http\News\Controller\GenerateNewsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Http/News/Controller/GenerateNewsController.php';
        include_once \dirname(__DIR__, 4).'/src/Application/UseCase/GenerateReportUseCase.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Port/ReportServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Services/ReportService.php';

        $container->services['App\\Infrastructure\\Http\\News\\Controller\\GenerateNewsController'] = $instance = new \App\Infrastructure\Http\News\Controller\GenerateNewsController(new \App\Application\UseCase\GenerateReportUseCase(new \App\Infrastructure\Services\ReportService(($container->services['kernel'] ?? $container->get('kernel', 1))), ($container->privates['App\\Infrastructure\\Repository\\NewsRepository'] ?? $container->load('getNewsRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Infrastructure\\Http\\News\\Controller\\GenerateNewsController', $container));

        return $instance;
    }
}
