<?php

namespace ContainerFLTWfKP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsIndexControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Infrastructure\Http\News\Controller\NewsIndexController' shared autowired service.
     *
     * @return \App\Infrastructure\Http\News\Controller\NewsIndexController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Http/News/Controller/NewsIndexController.php';
        include_once \dirname(__DIR__, 4).'/src/Application/UseCase/GetNewsList.php';

        $container->services['App\\Infrastructure\\Http\\News\\Controller\\NewsIndexController'] = $instance = new \App\Infrastructure\Http\News\Controller\NewsIndexController(new \App\Application\UseCase\GetNewsList(($container->privates['App\\Infrastructure\\Repository\\NewsRepository'] ?? $container->load('getNewsRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Infrastructure\\Http\\News\\Controller\\NewsIndexController', $container));

        return $instance;
    }
}
