<?php

namespace ContainerFLTWfKP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsCreateControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Infrastructure\Http\News\Controller\NewsCreateController' shared autowired service.
     *
     * @return \App\Infrastructure\Http\News\Controller\NewsCreateController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Http/News/Controller/NewsCreateController.php';
        include_once \dirname(__DIR__, 4).'/src/Application/UseCase/CreateNewsUseCase.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Factories/NewsFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Port/NewsServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Services/NewsService.php';

        $container->services['App\\Infrastructure\\Http\\News\\Controller\\NewsCreateController'] = $instance = new \App\Infrastructure\Http\News\Controller\NewsCreateController(new \App\Application\UseCase\CreateNewsUseCase(new \App\Application\Factories\NewsFactory(), ($container->privates['App\\Infrastructure\\Repository\\NewsRepository'] ?? $container->load('getNewsRepositoryService')), new \App\Infrastructure\Services\NewsService()));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Infrastructure\\Http\\News\\Controller\\NewsCreateController', $container));

        return $instance;
    }
}
