version: "3.2"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=codelibs-es
      - bootstrap.memory_lock=true
      - node.roles=master
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - type: bind
        source: ./elasticsearch/plugins
        target: /usr/share/elasticsearch/plugins
#      - type: bind
#        source: ./elasticsearch/data01
      - type: volume
        source: esdata01
        target: /usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=codelibs-es
      - bootstrap.memory_lock=true
      - node.roles=master
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - type: bind
        source: ./elasticsearch/plugins
        target: /usr/share/elasticsearch/plugins
#      - type: bind
#        source: ./elasticsearch/data02
      - type: volume
        source: esdata02
        target: /usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9201
        protocol: tcp
        mode: host
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - es01
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=codelibs-es
      - bootstrap.memory_lock=true
      - node.roles=master,voting_only,data
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - type: bind
        source: ./elasticsearch/plugins
        target: /usr/share/elasticsearch/plugins
#      - type: bind
#        source: ./elasticsearch/data03
      - type: volume
        source: esdata03
        target: /usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9202
        protocol: tcp
        mode: host
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - es01
      - es02
  es04:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es04
    environment:
      - node.name=es04
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=codelibs-es
      - bootstrap.memory_lock=true
      - node.roles=master,voting_only,data
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - type: bind
        source: ./elasticsearch/plugins
        target: /usr/share/elasticsearch/plugins
#      - type: bind
#        source: ./elasticsearch/data04
      - type: volume
        source: esdata04
        target: /usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9203
        protocol: tcp
        mode: host
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - es01
      - es02
      - es03

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  esdata04:
    driver: local

networks:
  esnet:
    driver: bridge

