version: "3.2"
services:
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=codelibs-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - type: bind
        source: ./elasticsearch/plugins
        target: /usr/share/elasticsearch/plugins
#      - type: bind
#        source: ./elasticsearch/data02
      - type: volume
        source: esdata02
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: true
    ports:
      - target: 9200
        published: 9201
        protocol: tcp
        mode: host
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - es01

volumes:
  esdata02:
    driver: local

