version: "3.2"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://es01:9200"
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    networks:
      - esnet
    depends_on:
      - es01
