<?php

namespace ContainerHB7lkW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Repository\NewsRepository' shared autowired service.
     *
     * @return \App\Infrastructure\Repository\NewsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryProxy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Repository/NewsRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Repository/NewsRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['App\\Infrastructure\\Repository\\NewsRepository'])) {
            return $container->privates['App\\Infrastructure\\Repository\\NewsRepository'];
        }

        return $container->privates['App\\Infrastructure\\Repository\\NewsRepository'] = new \App\Infrastructure\Repository\NewsRepository($a, ($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
