<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFLTWfKP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFLTWfKP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFLTWfKP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFLTWfKP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFLTWfKP\App_KernelDevDebugContainer([
    'container.build_hash' => 'FLTWfKP',
    'container.build_id' => '775971d3',
    'container.build_time' => 1747170466,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFLTWfKP');
