<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'news_index' => [[], ['_controller' => ['App\\Infrastructure\\Http\\News\\Controller\\NewsController', 'index']], [], [['text', '/api/index']], [], [], []],
    'generate_report' => [[], ['_controller' => ['App\\Infrastructure\\Http\\News\\Controller\\NewsController', 'generateReport']], [], [['text', '/api/generate_report']], [], [], []],
    'news_create' => [[], ['_controller' => ['App\\Infrastructure\\Http\\News\\Controller\\NewsController', 'create']], [], [['text', '/api/create_news']], [], [], []],
];
